/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:24e48e30-59d7-4188-b95e-a7186ae3ad81",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_Z52yJrYEV",
    "aws_user_pools_web_client_id": "a5ms2ggbf15ne2hrs6mjot1ge",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://5okdv4h3dbdmbikomunzvppzgq.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-5vakb53lt5cvtpr6tx2m4eutce",
    "aws_user_files_s3_bucket": "registermev2s385140234-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
